config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :farms, only: [:new, :create, :update, :edit, :destroy]

  resources :farms, only: [:show], as: :farm do
    resources :zones, only: [:new, :create, :index]
    member do
      get 'stats', to: 'farms#stats'
    end
  end
  resources :zones, only: [:show, :new, :edit, :update, :destroy] do
    resources :elements, only: [:new, :edit, :create, :update, :destroy]
  end
  resources :actions, only: [:create, :update]

  scope :community, as: :community do
    resources :farms, only: [:index]
  end

  resources :products, only: [:new, :create]
  resources :follows, only: [:create, :update]
end

app/models/farm.rb
class Farm < ApplicationRecord
  has_many :users, dependent: :nullify
  has_many :follows, dependent: :destroy
  has_many :zones, dependent: :destroy
  has_many :elements, through: :zones
  has_many :products, dependent: :destroy
  has_many :actions, through: :users, dependent: :destroy

  mount_uploader :photo, PhotoUploader

  validates :name, presence: true, uniqueness: true
  validates :address, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def creation_confirmation(garden)
    @farmn = farm
    mail(
      to:       @farm.user.email,
      subject:  "La ferme #{@farm.name} a bien été créée!"
    )
  end
end

app/controllers/farms_controller.rb
class FarmsController < ApplicationController
  before_action :set_farm, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      sql_query = " \
        farms.name ILIKE :query \
        OR farms.address ILIKE :query \
        OR users.name ILIKE :query \
      "
      @farms = policy_scope(Farm).joins(:users).where(sql_query, query: "%#{params[:query]}%")
    else
      @farms = policy_scope(Farm).all.order(name: :desc)
    end
    @markers = @farms.map do |farm|
      {
        lat: farm.latitude,
        lng: farm.longitude,
        infoWindow: { content: render_to_string(partial: "/farms/info_window", locals: { farm: farm }) }
      }
    end
    @products = Product.all
    @users = User.all
    @product = Product.new
    respond_to do |format|
      format.html
      format.js
    end
  end


  def new
    @farm = Farm.new
    authorize @farm
  end

  def create
    @farm = Farm.new(params_farm)
    @user = current_user
    @user.farm = @farm
    @farm.users << @user
    authorize @farm
    if @farm.save
      #TODO: Faire passer user.admin à true
      redirect_to farm_path(@farm)
    else
      render :new
    end
  end

  def show
    @farm = Farm.find(params[:id])
    authorize @farm
    @users = @farm.users
    @zones = @farm.zones
    @action = Action.new
    if params[:query].present?
      sql_query = " \
        actions.category ILIKE :query \
        OR actions.description ILIKE :query \
        OR elements.name ILIKE :query \
        OR zones.name ILIKE :query \
      "
      @actions = @farm.actions.joins(elements: :zone).where(sql_query, query: "%#{params[:query]}%")
    else
      @actions = @farm.actions.order(date: :desc)
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    authorize @farm
  end

  def update
    authorize @farm
    @farm.update(params_farm)
    redirect_to farm_path(@farm)
    authorize @farm
  end

  def destroy
    authorize @farm
    @farm.destroy
    redirect_to root_path
  end

  def stats
    @farm = Farm.find(params[:id])
    authorize @farm
    @zones = @farm.zones

    #charts1 - by zone
    @chart1_labels = []
    @chart1_data1 = []
    @chart1_data2 = []

    @zones.each do |zone|
      @chart1_labels << zone.name

      @sum = 0
      zone.elements.each do |element|
        @sum += element.actions.count
      end
      @chart1_data1 << @sum

      if current_user.follows.exists?
        sum = 0
        current_user.follows.each do |follow|
          follow.farm.zones.each do |follow_zone|
            if zone.name == follow_zone.name
              follow_zone.elements.each do |follow_element|
                sum += follow_element.actions.count
              end
            end
          end
        end
      sum = sum.fdiv(current_user.follows.count)
      @chart1_data2 << sum
      end
    end
    @chart1_datasets = [{
      label: 'Ma ferme',
      data: @chart1_data1,
      backgroundColor: '#4db53c',
      borderColor: '#4db53c',
      borderWidth: 1
    }, {
      label: 'Ma communauté (moyenne)',
      data: @chart1_data2,
      backgroundColor: '#336CBC',
      borderColor: '#336CBC',
      borderWidth: 1
    }
    ]

    #chart3 - by category
     @chart3_labels = [
       "Labourage",
       "Fertilisation",
       "Semis",
       "Repiquage",
       "Arrosage",
       "Désherbage",
       "Paillage",
       "Protection",
       "Récolte",
       "Nettoyage",
       "Distribution",
       "Autres"
     ]

    # @chart3_labels = [
    #   "preparing soil",
    #   "fertilisating",
    #   "sowing",
    #   "transplanting",
    #   "watering",
    #   "weeding",
    #   "mulching",
    #   "caring crops",
    #   "carrying",
    #   "cleaning",
    #   "sharing",
    #   "others"
    # ]

    # @data3_1 = [5, 5, 2, 1, 1, 0, 0, 1, 0, 0, 0, 0]
    # @data3_2 = [6, 6, 6, 5, 0, 1, 0, 3, 0, 0, 0, 0]

    @chart3_data1 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    hash = @farm.actions.group(:category).count
    hash.each do |k, v|
      @chart3_data1[@chart3_labels.find_index(k)] += v
    end

    @chart3_data2 = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    current_user.follows.each do |follow|
      hash = follow.farm.actions.group(:category).count
      hash.each do |k,v|
        @chart3_data2[@chart3_labels.find_index(k)] += v
      end
    end
    @chart3_data2.map do |element|
      element.fdiv(current_user.follows.count)
    end

    @chart3_datasets = [{
      label: 'Ma ferme',
      data: @chart3_data1,
      backgroundColor: 'rgba(77, 181, 60, 0.2)',
      borderColor: '#4db53c',
      borderWidth: 1
    },
    {
      label: 'Ma communauté (moyenne)',
      data: @chart3_data2,
      backgroundColor: 'rgba(51, 108, 188, 0.2)',
      borderColor: '#336CBC',
      borderWidth: 1
    },
  ]
  end

  private

  def set_farm
    @farm = Farm.find(params[:id])
  end

  def params_farm
    params.require(:farm).permit(:area, :photo, :name, :address)
  end
end

app/views/farms/_actions_list.html.erb
<div class="row farm-actions">
  <% if @farm.zones == [] %>
    <p class="error-message"><%= "Désolé, ces zones ne sont pas accessibles " %></p>
  <% else %>
      <div id= "searchbar">
        <%= form_tag farm_path(@farm), method: :get, remote: true do %>
          <%= text_field_tag :query, params[:query], class: "barwidth", placeholder: "Recherchez une action" %>
        <% end %>
      </div>
    </div>
    <% if @farm.users.include?(current_user) %>
      <div class="message text-left">
        <div class="message-name">
          <img class="plus-sign" src="http://res.cloudinary.com/bdmbdm/image/upload/v1528034422/plussign_square.png" data-toggle="modal" data-target="#myModal">
        </div>

        <div class="message-body">
          <p>Nouvelle action</p>
        </div>
      </div>
    <% end %>
  <% end %>
  <% @actions.each do |action| %>
    <div class="message">
      <div class="message-name filterDiv <%= action.category %>">
        <% if action.category == "Labourage" %>
          <img class="avatar-large" src="https://res.cloudinary.com/bdmbdm/image/upload/v1528188695/noun_1561630_cc.svg">
        <% elsif action.category == "Fertilisation" %>
          <img class="avatar-large" src="https://res.cloudinary.com/bdmbdm/image/upload/v1528188695/noun_1042097_cc.svg">
        <% elsif action.category == "Semis" %>
          <img class="avatar-large" src="https://res.cloudinary.com/bdmbdm/image/upload/v1527671029/seed.svg">
        <% elsif action.category == "Repiquage" %>
          <img class="avatar-large" src="https://res.cloudinary.com/bdmbdm/image/upload/v1528188695/noun_1205722_cc.svg">
        <% elsif action.category == "Arrosage" %>
          <img class="avatar-large" src="https://res.cloudinary.com/bdmbdm/image/upload/v1528188695/noun_1240203_cc.svg">
        <% elsif action.category == "Désherbage" %>
          <img class="avatar-large" src="https://res.cloudinary.com/bdmbdm/image/upload/v1528189035/noun_984560_cc.svg">
        <% elsif action.category == "Paillage" %>
          <img class="avatar-large" src="https://res.cloudinary.com/bdmbdm/image/upload/v1528188695/noun_1240202_cc.svg">
        <% elsif action.category == "Protection" %>
          <img class="avatar-large" src="https://res.cloudinary.com/bdmbdm/image/upload/v1528189177/noun_1002074_cc.svg">
        <% elsif action.category == "Récolte" %>
          <img class="avatar-large" src="https://res.cloudinary.com/bdmbdm/image/upload/v1527671027/brouette.svg">
        <% elsif action.category == "Nettoyage" %>
          <img class="avatar-large" src="https://res.cloudinary.com/bdmbdm/image/upload/v1528189352/noun_1551479_cc.svg">
        <% elsif action.category == "Distribution" %>
          <img class="avatar-large" src="https://res.cloudinary.com/bdmbdm/image/upload/v1527671030/selling.svg">
        <% else %>
          <img class="avatar-large" src="https://res.cloudinary.com/bdmbdm/image/upload/v1528188695/noun_1205722_cc.svg">
        <% end %>
      </div>

      <div class="message-body products date">
        <p><%= action.date.strftime("%d/%m/%Y") %></p>
         <!-- #.strftime("%A, %b %d") -->
      </div>
      <div class="message-body products">
        <p><strong><%= action.category.upcase %></strong></p>
      </div>
        <div class="message-body productsi">
          <p><strong><%= action.element.name %></strong> : <%= action.description %></p>
        </div>
        <div class="message-body elements">
          <p><%= link_to action.element.zone.name, zone_path(action.element.zone) %></p>
        </div>

      <div class="message-body">
        <% if @farm.users.include?(current_user)%>
          <% if action.status %>
            <div class="text-center">
              <div><i class="fas fa-check done"></i></div>
              <%= link_to "annuler", action_path(action), method: :patch, remote: true, class: "icon done" %>
            </div>
          <% else %>
            <%= link_to "Je l'ai fait", action_path(action), method: :patch, remote: true, class: "button-contact" %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/farms/_follow_button.html.erb
<%= link_to follow_path(@garden), method: :patch, remote: true, class: "icon follow-btn" do %>
  <% if current_user.follow?(@garden) %>
    <button class="button-contact followbtn">Ne plus suivre</button>
  <% else %>
    <button class="button-contact followbtn">Suivre</button>
  <% end %>
<% end %>

app/views/farms/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.input :name %>
  <%= f.input :address, input_html: { id: 'garden_address'}, input_html: { class: "select2" } %>
  <%= f.input :area, placeholder: 'ex: 1000 m2' %>
  <%= f.input :photo %>
  <%= f.submit 'go!', class: "btn btn-home btn-lg" %>
<% end %>

app/views/farms/_info_window.html.erb
<% follow = current_user.follow?(garden) %>
<%= cl_image_tag garden.photo, class: "img-map" %>
<%= link_to follows_path(garden_id: garden.id), method: :post, class: "icon" do %>
  <i class="fas fa-heart <%= "followed" if follow %>" ></i>
<% end %>
<h2 class="mapi"><%= garden.name %></h2>
<p class="mapi"><%= garden.address %></p>
<!--   </div>
  </div> -->

<%= link_to garden_path(garden) do %>
<!-- </div> -->
  <div class="card-link">
    <p>discover</p>
  </div>
<% end %>

app/views/farms/_my_followers.html.erb
<h4 class="text-center">Mes amis</h4>
<% current_user.follows.each do |follow| %>
  <% follow.garden.users.each do |user| %>
    <div class= "col-xs-6 no-padding"><%= cl_image_tag user.avatar, class: "avatar-medium shared"%></div>
  <% end %>
<% end %>

app/views/farms/_products.html.erb
<div class="row">
  <div class="items text-center">
    <h4>Produits partagés dans ma communauté</h4>
    <br>
  </div>

  <% current_user.follows.each do |follow| %>
    <% follow.garden.products.each do |product| %>
      <div class="message">
        <div class="message-name">
          <%= cl_image_tag product.photo, class: "photo-produit"  %>
        </div>
        <div class="message-body product">
          <p><strong><%= product.description %> <%= product.element.name.upcase %> x <%= product.quantity %></strong></p>
        </div>
        <div class="message-body">
          <p>Partagé par <%= product.element.zone.garden.users[0].name %></p>
        </div>
        <div class="message-body adress-garden">
          <h6><%= product.element.zone.garden.name.upcase %></h6>
        </div>
        <div class="message-body">
          <button class="button-contact sweet-1" data-toggle="modal" data-target="#myModal-message"> CONTACT </button>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/farms/_rightsideindex.html.erb
<div id="map-markers" data-markers="<%= markers.to_json %>">
  <% gardens.each do |garden| %>
    <% unless garden == current_user.garden %>
      <div class="col-xs-12 col-sm-6">
        <div class="card">
          <%= cl_image_tag garden.photo, class: "card-img-top" %>
          <%= link_to follows_path(garden_id: garden.id), method: :post, remote: true, class: "icon" do %>
            <i class="fas fa-heart <%= "followed" if current_user.follow?(garden) %>" ></i>
          <% end %>
           <!--  <a href="#" class="icon"><i class="fas fa-seedling"></i></a> -->
          <%= link_to garden_path(garden) do %>
            <div class="overlay">
              <%= cl_image_tag garden.users[0].avatar, class: "avatar card-avatar" %>
              <div class="text">
                <h2><%= garden.name %></h2>
                <p><%= garden.address %></p>
              </div>
            </div>
            <div class="card-link">
              <p>découvrir</p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/farms/edit.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.12), rgba(0,0,0,0.11)), url(http://res.cloudinary.com/bdmbdm/image/upload/v1527854895/qwyyhcbciic97mmcvfys.jpg); background-size: cover!important;">
  <div class="form">
    <div class="row">
      <h1>Modifier les informations de votre ferme</h1>
       <% if policy(@garden).edit? %>
        <%= render 'form', garden: @garden %>
      <% end %>
    </div>
  </div>
</div>

app/views/farms/index.html.erb
<%= render 'shared/banner-community' %>

<div class="container map">

  <div class="wrapper wrapper-3 animated fadeInUp">
    <h1 class="how text-center">Rejoignez la communauté de permaculteurs</h1>
  </div>

  <div class="tab animated fadeInUp">
    <button class="tablinks default" data-tab="Follow"><h1>Toutes les fermes</h1></button>
    <button class="tablinks" data-tab="Shared"><h1>Ma communauté</h1></button>
  </div>


  <div id="Follow" class="tabcontent active animated fadeInUp">
    <div class="row zones-garden">
      <div class="col-xs-12 col-md-6">
        <div id= "search-community">
          <%= form_tag community_gardens_path, method: :get, remote: true do %>
            <%= text_field_tag :query, params[:query], class: "barwidth", placeholder: "trouver une ferme, construire sa communauté" %>
          <% end %>
        </div>
        <br><br>
        <div
          id="map"
          style="min-width: 500px; min-height: 600px;"
          data-markers="<%= @markers.to_json %>">
        </div>
      </div>


      <div class="col-xs-12 col-md-6 right-side-index">
        <%= render "rightsideindex", gardens: @gardens, markers: @markers %>
      </div>
    </div>
  </div>


  <!-- this is the shared section -->
  <div id="Shared" class="tabcontent">

    <div class="row">
      <div class="col-xs-2 myfollowers no-padding">
        <%= render "my_followers" %>
      </div>

    <div class="col-xs-8 col-xs-offset-1">
      <div class="products">
        <%= render "products" %>
      </div>
  </div>
  <!-- this is the end of log section -->
  <br><br>
  <br><br>
  </div>
  <!-- <div>
    <h1>Followed</h1>
    <#% current_user.follows.each do |follow| %>
    <p><%#= follow.garden.name %></p>
    <%# end %>
  </div>
   -->
  <div class="modal fade" id="myModal-message" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content form">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Envoyer un message</h4>
        </div>
        <div class="modal-body">
          <div class="form-actions">
              <div>
                <br>
                <label for="name">Votre prénom :</label>
                <input type="text" id="name" name="user_name" class="form-control">
              </div>
              <div>
                <br>
                <label for="msg">Votre message :</label>
                <textarea id="msg" name="user_message" class="form-control msg"></textarea>
              </div>
              <div>
                <input type="submit" value="envoyer" class="btn btn-home btn-lg" onclick="confirmSent()">
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>
</div>

app/views/farms/index.js.erb
document.querySelector(".right-side-index").innerHTML = '<%= j render "gardens/rightsideindex", gardens: @gardens, markers: @markers %>';
drawMap();

app/views/farms/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.12), rgba(0,0,0,0.11)), url(https://images.unsplash.com/photo-1431631927486-6603c868ce5e?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=31cfb792a10418a51f4a1e609e089a06&auto=format&fit=crop&w=1950&q=80); background-size: cover!important;">
  <div class="form">
    <div class="row">
      <h1>Créer une ferme</h1>
      <% if policy(Garden).create? %>
        <%= render 'form', garden: @garden %>
      <% end %>
    </div>
  </div>
</div>

app/views/farms/show.html.erb
<% if @farm == current_user.farm %>

  <%= render 'shared/banner-dashboard' %>
      <div class="zone-name">
      <h1>MA FERME</h1>
      </div>
    </div>
  <div class="row meteo animated fadeInUp">
    <a class="weatherwidget-io open-link" href="https://forecast7.com/fr/48d530d75/longny-au-perche/" data-font="Open Sans" data-icons="Climacons Animated" data-mode="Forecast" data-theme="pure" >Longny-au-Perche, France</a>
    <script>
    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src='https://weatherwidget.io/js/widget.min.js';fjs.parentNode.insertBefore(js,fjs);}}(document,'script','weatherwidget-io-js');
    </script>
  </div>

<% else %>
<%= render 'shared/banner-dashboard' %>

  <% @users.each do |user| %>
    <% if user.farm_id == @farm.id %>
        <div class="zone-name autre">
          <div class="row">
            <div class="col-xs-12 col-md-2 col-md-offset-2">
              <div><%= cl_image_tag user.avatar, class: "avatar-other" %></div>
              <div> <%= render "follow_button", farm: @farm %></div>
            </div>
            <div class="col-xs-12 col-md-5">
              <div class="title-other">
                <h1 class="text-left">BIENVENUE CHEZ <%= user.name.upcase %></h1>
                  <p><%= @farm.name %></p>
                  <p><%= @farm.address %></p>
              </div>
            </div>
        </div>
      </div>

        </div>
    <% end %>
  <% end %>
<% end %>

<div class="container show-farm animated fadeInUp">
  <!-- this is the zone section -->
  <br><br>
  <div class="tab">
    <% if @farm.users.include?(current_user) %>
      <button class="tablinks" data-tab="Farm"><h1>Mes zones</h1></button>
      <button class="tablinks default" data-tab="Actions"><h1>Mes actions</h1></button>
      <!-- <button class="tablinks" data-tab="Shares"><h1>my shares</h1></button> -->
    <% else %>
      <button class="tablinks default" data-tab="Farm"><h1>Zones</h1></button>
      <button class="tablinks" data-tab="Actions"><h1>Actions</h1></button>
    <!--   <button class="tablinks" data-tab="Shares"><h1>shares</h1></button> -->
    <% end %>
  </div>
  <div id="Farm" class="tabcontent active">
    <div class="row zones-farm">
      <% if @zones == [] %>
        <p class="error-message">Désolé, vous n'avez pas encore de zones</p>
      <% else %>
        <% if @farm.users.include?(current_user) %>
          <div class="col-xs-12 col-md-3">
            <div class="card">
              <%= cl_image_tag "https://res.cloudinary.com/bdmbdm/image/upload/v1528191161/Plan_de_travail_123.png", class: "card-img-top", width: 10 %>
              <%= link_to new_farm_zone_path(@farm) do %>
                <div class="overlay">
                  <div class="text">
                    <h5>J'ajoute une zone</h5>
                  </div>
                </div>
                <div class="card-link">
                  <p>Ajouter</p>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>

      <% @farm.zones.each do |zone| %>
        <div class="col-xs-12 col-md-3">
          <div class="card">
          <%= cl_image_tag zone.photo, class: "card-img-top" %>
          <%= link_to zone_path(zone) do %>
            <div class="overlay">
              <div class="text">
                <p>Superficie : <%= zone.area %>m2</p>
                <% unless zone.actions.empty? %>
                  <% if @farm == current_user.farm %>
                    <p>Votre dernière action : le <br><%= zone.actions.last.date.strftime("%d/%m/%Y")%></p>
                  <% else %>
                    <p>Dernière action : le <br><%= zone.actions.last.date.strftime("%d/%m/%Y")%></p>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="card-link">
              <p><%= zone.name %></p>
            </div>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <!-- this is the end of the zone section -->
  <!-- this is the action section -->
  <div id="Actions" class="tabcontent">
    <%= render 'actions_list', actions: @actions, farm: @farm %>
  </div>
  <!-- this is the end of aciton section -->
  </div>

<div id="Shares" class="tabcontent">
  <div class="row farm-actions">
    <% if @farm.zones == [] %>
      <p class="error-message"><%= "Ajoutez une zone" %></p>
    <% else %>
      <% if @farm.users.include?(current_user) %>
        <div class="message text-left">
          <div class="message-name">
            <img class="plus-sign" src="http://res.cloudinary.com/bdmbdm/image/upload/v1528034422/plussign_square.png" data-toggle="modal" data-target="#myModalShares">
          </div>
          <div class="message-body">
            <p>Je partage avec ma communauté</p>
          </div>
        </div>
      <% end %>
      <% @actions.each do |action| %>
        <div class="message">
          <div class="message-name">
            <img class="avatar-large" src="https://res.cloudinary.com/bdmbdm/image/upload/v1527671029/veggies_and_fruits.svg">
          </div>
          <div class="message-body">
            <p><%= action.date.strftime("%d/%m/%Y") %></p>
          </div>
          <div class="message-body products">
            <p><strong><%= action.category.upcase %></strong></p>
          </div>
            <div class="message-body productsi">
              <p><strong><%= action.element.name %></strong> : <%= action.description %></p>
            </div>
        </div>
      <% end %>
    <% end %>
  </div>

<br><br>

</div>



      <%# @garden.zones.each do |zone|%>
        <%# zone.elements.each do |element| %>
          <%# element.log_scopes.each do |log_scope| %>
            <%# log_scope.logs.each do |log| %>
              <!-- <div> -->
      <!--           <h1><%#= log.date %></h1> -->
                <!-- <p><%#= log.status %></p> -->
                <!-- <p><%#= log.category %></p> -->
              <!-- </div> -->
            <%# end %>
          <%# end %>
         <%# end %>
  </div>
</div>

  <!-- Modal -->
<div class="modal fade" id="myModal" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content form">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Enregistrer une action</h4>
      </div>
      <div class="modal-body">
        <div class="form-action">
          <%= simple_form_for @action do |f| %>
            <%= f.input :date, as: :string, input_html: { class: "datepicker"} %>
            <%= f.input :category, label: 'Type d\'action', collection: Action::ACTIONS, prompt:'Choisissez une action', input_html: { class: "select2" } %>
            <%= f.input :description %>
            <%= hidden_field_tag :farm_id, @farm.id %>
<!--             <p> On which zones? </p>
 -->            <%#= f.simple_fields_for :zones do |v|  %>
              <%#= v.collection_check_boxes :name, @garden.zones, :id, :name %>
            <%# end %>
            <p> Sur quels éléments ? </p>
            <div class="block-party">
              <%= f.simple_fields_for :elements do |e| %>
                <%= e.collection_radio_buttons :name, @farm.elements, :id, :name %>
              <% end %>
            </div>
              <%#= f.association :elements, collection: zone.elements, as: :check_boxes %>
            <%= f.submit 'Enregistrer', class: 'btn btn-home btn-lg' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="myModalShares" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content form">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">J'enregistre une action</h4>
      </div>
      <div class="modal-body">
        <div class="form-action">
          <%= simple_form_for @action do |f| %>
            <%= f.input :date, as: :string, input_html: { class: "datepicker" } %>
            <%#= f.input :category, collection: Log::ACTIONS, prompt:"which action would you like to log?", input_html: { class: "select2" } %>
            <p> Que voulez-vous partager? </p>
            <%= f.simple_fields_for :elements do |e| %>
              <%= e.collection_check_boxes :name, @farm.elements, :id, :name, class: 'form-check' %>
            <% end %>
<!--             <p> From which zones? </p>
 -->            <%#= f.simple_fields_for :zones do |v|  %>
              <%#= v.collection_check_boxes :name, @garden.zones, :id, :name %>
            <%# end %>
            <%= f.input :description %>
            <%= hidden_field_tag :farm_id, @farm.id %>
            <br>
            <br><br>
              <%#= f.association :elements, collection: zone.elements, as: :check_boxes %>
              <%#= hidden_field_tag :zone_id, zone.id %>
              <br><br>
            <%= f.submit 'Je partage avec ma communauté', class: 'btn btn-home btn-lg' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<% if @action.errors.any? %>
<%= javascript_pack_tag 'display_modal' %>
<% end %>

app/views/farms/show.js.erb
document.querySelector("#Logs").innerHTML = '<%= j render "gardens/logslist" %>';