config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :farms, only: [:new, :create, :update, :edit, :destroy]

  resources :farms, only: [:show], as: :farm do
    resources :zones, only: [:new, :create, :index]
    member do
      get 'stats', to: 'farms#stats'
    end
  end
  resources :zones, only: [:show, :new, :edit, :update, :destroy] do
    resources :elements, only: [:new, :edit, :create, :update, :destroy]
  end
  resources :actions, only: [:create, :update]

  scope :community, as: :community do
    resources :farms, only: [:index]
  end

  resources :products, only: [:new, :create]
  resources :follows, only: [:create, :update]
end

app/views/shared/_banner-community.html.erb
<div class="banner-dash" style="background-image: linear-gradient(rgba(0,0,0,0.12), rgba(0,0,0,0.11)), url(https://res.cloudinary.com/bdmbdm/image/upload/v1528130936/photo-1468357161629-c3c530741678.jpg)">
</div>

app/views/shared/_banner-dashboard.html.erb
<div class="banner-dash" style="background-image: linear-gradient(rgba(0,0,0,0.12), rgba(0,0,0,0.11)), url(<%= @farm.photo %>)">
</div>

app/views/shared/_banner-zone.html.erb
<div class="banner-dash" style="background-image: linear-gradient(rgba(0,0,0,0.12), rgba(0,0,0,0.11)), url(<%= @zone.photo %>)">
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.3)), url(https://res.cloudinary.com/bdmbdm/image/upload/v1530018614/landscape-1490800142-vegetable-patch.jpg); background-size: cover!important;" >
  <div class="banner-content">
    <br><br>
    <h1><span id="banner-typed-text"></span><br>votre ferme en permaculture</h1>
    <br>
    <%= link_to "démarrer", new_user_registration_path, class: "btn btn-home btn-lg animated zoomIn" %>
    <a href="mailto:contact@radicl.org" class="btn btn-home btn-lg contactez">contactez-nous</a>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    © radicl team - 2018 - le wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "radicl-logo-3.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <% if current_user.farm.nil? == false %>
        <!-- Links when logged in -->
        <%= link_to "Ma ferme", farm_path(current_user.farm), class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Tableau de bord", stats_farm_path(current_user.farm), class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Communauté", community_farms_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% else %>
        <%= link_to "Communauté", community_farms_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
        <!-- Avatar photo -->
          <% if current_user.avatar.present? %>
            <%= cl_image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% else %>
            <%= cl_image_tag 'male-farmer_1f468-200d-1f33e', class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <% end %>

          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu" aria-labelledby="navbar-wagon-menu">
            <li>
              <%= link_to edit_user_registration_path do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profil") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i>  <%= t(".sign_out", default: "Déconnexion") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Se connecter"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Ma ferme</a></li>
        <li><a href="#">Mes zones</a></li>
        <li><a href="#">Aide</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_new-log.html.erb
<h1>Log an action</h1>
<%= simple_form_for [@user, @log] do |f| %>
  <%= f.input :date, required: true %>
  <%= f.input :category, required: true %>
  <%= f.input :description, required: false %>
  <%= f.input :quantity, as: :integer, required: true %>
  <%= f.submit "add an element", class: "btn btn-primary" %>
<% end %>