config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :farms, only: [:new, :create, :update, :edit, :destroy]

  resources :farms, only: [:show], as: :farm do
    resources :zones, only: [:new, :create, :index]
    member do
      get 'stats', to: 'farms#stats'
    end
  end
  resources :zones, only: [:show, :new, :edit, :update, :destroy] do
    resources :elements, only: [:new, :edit, :create, :update, :destroy]
  end
  resources :actions, only: [:create, :update]

  scope :community, as: :community do
    resources :farms, only: [:index]
  end

  resources :products, only: [:new, :create]
  resources :follows, only: [:create, :update]
end

app/views/pages/home.html.erb
<%= render 'shared/banner' %>
<div class="container animated anim-scroll">
  <div class="wrapper">
    <h1 class="how text-center">Comment ça marche ?</h1>
    <div class="row">
      <br><br><br>
      <%= link_to new_farm_path do %>
        <div class="col-xs-12 col-sm-3">
          <div class="card-icon">
            <img src="https://res.cloudinary.com/bdmbdm/image/upload/v1527671032/farm.svg" alt="">
          </div>
          <p class="text-center">Créez votre ferme et suivez les fermes de votre région</p>
        </div>
      <% end %>
      <div class="col-xs-12 col-sm-3">
        <div class="card-icon">
          <img src="https://res.cloudinary.com/bdmbdm/image/upload/v1527697260/circles2.svg" alt="">
        </div>
        <p class="text-center">Ajoutez vos zones de permaculture</p>
      </div>
      <div class="col-xs-12 col-sm-3">
        <div class="card-icon">
          <img src="https://res.cloudinary.com/bdmbdm/image/upload/v1527671027/watering.svg" alt="">
        </div>
        <p class="text-center">Pilotez votre activité au quotidien</p>
      </div>
      <div class="col-xs-12 col-sm-3">
        <div class="card-icon">
          <img src="http://res.cloudinary.com/bdmbdm/image/upload/v1527697464/share.svg" alt="">
        </div>
        <p class="text-center">Partagez votre expérience & vos produits</p>
      </div>
    </div>
  </div>
</div>

<% if user_signed_in? %>
  <div class="wrapper-2">
    <h1 class="how text-center">Découvrez les fermes de votre région</h1>
    <br><br>
    <div class="row">
      <% @farms.each do |farm| %>
        <% unless farm == current_user.farm %>
          <div class="col-xs-12 col-sm-3">
            <div class="card">
              <%= cl_image_tag farm.photo, class: "card-img-top" %>
              <% if user_signed_in? %>
                <% follow = current_user.follow?(farm) %>
                <%= link_to follows_path(farm_id: farm.id), method: :post, class: "icon" do %>
                  <i class="fas fa-heart <%= "followed" if follow %>" ></i>
                <% end %>
              <% end %>
              <%= link_to farm_path(farm) do %>
                <div class="overlay">
                  <%= cl_image_tag farm.users[0].avatar, class: "avatar card-avatar" %>
                  <div class="text">
                    <h2><%= farm.name %></h2>
                    <p><%= farm.address %></p>
                  </div>
                </div>
                <div class="card-link">
                  <p>découvrir</p>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
  <br>
<%# if user_signed_in? %>
  <!-- <div class="text-center animated zoomIn"> <%#= link_to "Accéder à votre ferme", farm_path(current_user.farm), class: "btn btn-home btn-lg text-center green-button" %>
  </div> -->
<%# end %>
</div>