config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :farms, only: [:new, :create, :update, :edit, :destroy]

  resources :farms, only: [:show], as: :farm do
    resources :zones, only: [:new, :create, :index]
    member do
      get 'stats', to: 'farms#stats'
    end
  end
  resources :zones, only: [:show, :new, :edit, :update, :destroy] do
    resources :elements, only: [:new, :edit, :create, :update, :destroy]
  end
  resources :actions, only: [:create, :update]

  scope :community, as: :community do
    resources :farms, only: [:index]
  end

  resources :products, only: [:new, :create]
  resources :follows, only: [:create, :update]
end

app/models/zone.rb
class Zone < ApplicationRecord
  belongs_to :farm
  has_many :elements, dependent: :destroy
  has_many :actions, through: :elements

  mount_uploader :photo, PhotoUploader

  validates :name, presence: true
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :set_zone, only: [:show, :edit, :update, :destroy]

  def new
    @garden = Garden.find(params[:garden_id])
    @zone = Zone.new
    authorize @zone
  end

  def create
    @garden = Garden.find(params[:garden_id])
    @zone = Zone.new(zone_params)
    @zone.garden = @garden
    authorize @zone
    if @zone.save
      redirect_to new_zone_element_path(@zone)
    else
      render :new
    end
  end

  def show
    authorize @zone
    @zone = Zone.find(params[:id])
    @garden = @zone.garden
    @log = Log.new
    @elements = Element.all
    @log_scopes = LogScope.all
  end

  def edit
    authorize @zone
    @garden = @zone.garden
  end

  def update
    authorize @zone
    @zone.update(zone_params)
    redirect_to zone_path(@zone)
  end

  def destroy
    authorize @zone
    @zone.destroy
    redirect_to garden_path(@zone.garden)
  end

  private

  def set_zone
    @zone = Zone.find(params[:id])
  end

  def zone_params
    params.require(:zone).permit(:name, :area, :photo, :garden_id)
  end
end

app/views/zones/_form.html.erb
<%= simple_form_for [garden, zone] do |f| %>
  <%= f.input :name %>
  <%= f.input :area, placeholder: "for ex: 1000m2" %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit 'go!', class: "btn btn-home btn-lg" %>
<% end %>

app/views/zones/edit.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.12), rgba(0,0,0,0.11)), url(https://res.cloudinary.com/bdmbdm/image/upload/v1527843409/photo-1486328228599-85db4443971f.jpg); background-size: cover!important;">
  <div class="form">
    <div class="row">
      <h1>edit your info</h1>
      <% if policy(@zone).edit? %>
        <%= render 'form', zone: @zone %>
      <% end %>
    </div>
  </div>
</div>

app/views/zones/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.12), rgba(0,0,0,0.11)), url(https://res.cloudinary.com/bdmbdm/image/upload/v1527843409/photo-1486328228599-85db4443971f.jpg); background-size: cover!important">
  <div class="form">
    <div class="row">
      <h2>Ajouter une zone à votre ferme</h2>
      <br>
      <% if policy(@zone).create? %>
        <%= render 'form', garden: @garden, zone: @zone %>
      <% end %>
    </div>
  </div>
</div>

app/views/zones/show.html.erb
<%= render 'shared/banner-zone' %>

<div class="zone-name zoni">
  <h1><%= @zone.name.upcase %></h1>
    <%= link_to edit_zone_path(@zone) do %>
      <i class="far fa-edit"></i>
    <% end %>
  <p><%= @zone.garden.name %></p>
  <%= link_to zone_path(@zone),
    method: :delete,
    data: { confirm: "Are you sure?" } do %>
    <i class="far fa-trash-alt"></i>
  <% end %>
</div>

<div class="container show-garden">
<!-- this is the zone section -->
  <br><br>
  <div class="tab">
    <button class="tablinks default" data-tab="elements"><h1>my elements</h1></button>
    <button class="tablinks" data-tab="elements-logs"><h1>my logs</h1></button>
  </div>

  <div id="elements" class="tabcontent active">
    <div class="row">
      <% @elements.each do |element| %>
        <% if element.zone_id == @zone.id %>
          <div class="col-xs-12 col-md-3">
            <%= content_tag(:div, class: "card garden", style:"background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.2)), url(https://res.cloudinary.com/bdmbdm/image/upload/v1527861929/a7pneilafaclnlzhogdh.jpg") do %>
              <div class="card-description-zone">
                <h3><%= element.name%></h3>
                <%= link_to edit_zone_element_path(element) do %>
                  <i class="far fa-edit"></i>
                <% end %>
                <p><%= element.quantity %></p>
                <p>last log: 12/01/2018</p>
                <%= link_to zone_element_path(element),
                  method: :delete,
                  data: { confirm: "Are you sure?" } do %>
                  <i class="far fa-trash-alt"></i>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="plus">
      <% if @garden.users.include?(current_user) %>
        <%= link_to new_zone_element_path(@zone) do %>
          <img src="https://res.cloudinary.com/bdmbdm/image/upload/v1527684634/Fichier_1-100.jpg" alt="">
        <% end %>
      <% end %>
    </div>
  </div>

  <div id="elements-logs" class="tabcontent">
    <div class="row garden-logs">
      <% @elements.each do |element| %>
        <% if element.zone_id == @zone.id %>
          <% @log_scopes.each do |log_scope| %>
            <% if log_scope.element_id == element.id %>
              <div class="message">
                <div class="message-name">
                  <img class="avatar-large" src="https://res.cloudinary.com/bdmbdm/image/upload/v1527671029/veggies_and_fruits.svg">
                  <p><%= log_scope.log.date %></p>
                  <p><strong><% if log_scope.log.status = true %>
                    <span class="badge badge-success">good job!</span>
                  <% else %>
                    <span class="badge badge-warning">to be done</span>
                    <p>plan the log</p>
                  <% end %></strong></p>
                </div>
                <div class="message-body">
                  <h4><strong><%= log_scope.log.category %></strong> on <%= log_scope.element.name %></h4>
                  <p><%= log_scope.log.description %></p>
                </div>
              </div>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <div class="plus mod">
      <% if @garden.users.include?(current_user) %>
        <button class="plus" data-toggle="modal" data-target="#myModal">
          <img src="https://res.cloudinary.com/bdmbdm/image/upload/v1527684634/Fichier_1-100.jpg" alt="">
        </button>
      <% end %>
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content form">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title" id="myModalLabel">Commit your log</h3>
      </div>
      <div class="modal-body">
        <div class="form-log">
          <% if policy(@log).create? %>
            <%= simple_form_for @log do |f| %>
              <%= f.input :date, as: :date, input_html: { class: "select2" } %>
              <%= f.input :category, collection: Log::ACTIONS, prompt:"which action would you like to log?", input_html: { class: "select2" } %>
              <%= f.input :description %>
              <%= f.input :quantity %>
              <%= f.association :elements, collection: @zone.elements, as: :check_boxes %>
              <%= hidden_field_tag :zone_id, @zone.id %>
              <br>
              <%= f.submit 'save your action', class: 'btn btn-home btn-lg' %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% if @log.errors.any? %>
  <%= javascript_pack_tag 'display_modal' %>
<% end %>